# Generated by Django 3.2.10 on 2021-12-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfGame', models.CharField(blank=True, max_length=150, null=True)),
                ('Platform', models.CharField(blank=True, max_length=150, null=True)),
                ('YearOfRelease', models.CharField(blank=True, max_length=150, null=True)),
                ('YearOfReleaseDate', models.DateField(null=True)),
                ('Genre', models.CharField(blank=True, max_length=150, null=True)),
                ('GlobalSale', models.CharField(blank=True, max_length=150, null=True)),
                ('Critics', models.CharField(blank=True, max_length=150, null=True)),
                ('UserScore', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
