
# Generated by Django 3.2.4 on 2022-01-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastmodel',
            old_name='Critics',
            new_name='Critic_Score',
        ),
        migrations.RenameField(
            model_name='forecastmodel',
            old_name='GlobalSale',
            new_name='Global_Sale',
        ),
        migrations.RenameField(
            model_name='forecastmodel',
            old_name='NameOfGame',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='forecastmodel',
            old_name='UserScore',
            new_name='Publisher',
        ),
        migrations.RenameField(
            model_name='forecastmodel',
            old_name='YearOfRelease',
            new_name='User_Score',
        ),
        migrations.AddField(
            model_name='forecastmodel',
            name='Year_of_Release',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
